name: Update Files
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Set up jq and GNU Parallel
      run: |
        sudo apt-get update
        sudo apt-get install -y jq parallel

    - name: Update files from easyinstall.json
      run: |
        jq -r 'to_entries | sort_by(.key)[] | "curl -fsSL -o \(.key) \(.value.installer_source)"' easyinstall.json | parallel --gnu -j 4

    - name: Commit and push script changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Update files' || echo "No changes to commit"
        git push
